In [3]:
import pandas as pd

df = pd.read_csv("./results_full.txt")

In [4]:
df.head()

,Interaction index,Player index,Opponent index,Repetition,Player name,Opponent name,Actions,Score,Score difference,Turns,...,DD count,CC to C count,CC to D count,CD to C count,CD to D count,DC to C count,DC to D count,DD to C count,DD to D count,Good partner
0,0,0,0,0,LLM(gpt-3.5-turbo)(selfish),LLM(gpt-3.5-turbo)(selfish),DDCDDDDDDDDDDCDDDDDD,22,9,20,...,13,0,0,0,2,1,4,1,11,0
1,0,0,0,0,LLM(gpt-3.5-turbo)(selfish),LLM(gpt-3.5-turbo)(selfish),CDDDDDCDDDDDCDCDDDCD,13,-9,20,...,13,0,0,0,5,1,1,3,9,1
2,1,0,1,0,LLM(gpt-3.5-turbo)(selfish),LLM(gpt-3.5-turbo)(adversarial),DDCDDDDDDDDDDCDDDDDD,40,24,20,...,9,0,1,0,1,1,7,1,8,0
3,1,1,0,0,LLM(gpt-3.5-turbo)(adversarial),LLM(gpt-3.5-turbo)(selfish),DCDCDCCDCDCDDCCDCDDC,16,-24,20,...,9,1,0,1,7,1,0,7,2,1
4,2,1,0,0,LLM(gpt-3.5-turbo)(adversarial),LLM(gpt-3.5-turbo)(selfish),CCCDDCDCDCDCDDCDCDCD,24,-15,20,...,8,1,2,1,6,1,1,6,1,1

In [8]:
mean_scores = df.groupby('Player name')['Score'].mean()
ranked_df = pd.DataFrame(mean_scores).rename(columns={'Score': 'Mean Score'})
ranked_df

                                 Mean Score
Player name
LLM(gpt-3.5-turbo)(adversarial)   40.000000
LLM(gpt-3.5-turbo)(cooperative)   40.833333
LLM(gpt-3.5-turbo)(selfish)       39.833333

In [5]:
df.pivot_table(index='Player name', columns='Opponent name', values='Score', aggfunc='mean')

Opponent name,LLM(gpt-3.5-turbo)(adversarial),LLM(gpt-3.5-turbo)(cooperative),LLM(gpt-3.5-turbo)(selfish)
Player name,,,
LLM(gpt-3.5-turbo)(adversarial),41.0,59.0,20.0
LLM(gpt-3.5-turbo)(cooperative),42.5,56.5,23.5
LLM(gpt-3.5-turbo)(selfish),39.5,62.5,17.5